### ISSUE TITLE
Consider asmjit 

### ISSUE THREAD

**Issue by mrexodia** [zerosum0x0/WinREPL#1]
You mention the GPL requirement, with asmtk you could avoid this if needed. It is also much easier to include directly in this repository as a submodule and outputs much a much smaller lib file.

https://github.com/asmjit/asmtk

**Comment by zerosum0x0** [comment]
GPLv2 isn't my favorite license but I guess it's fine for something small like this. Thanks for linking that project though, I hadn't seen it before.

Also after working with the Windows debugging APIs, I'm surprised you were the first one to finally get us an x64 debugger after 10 years! They're really nice to work with and x64 could have been dropped into Olly in an afternoon.
